components:
    schemas:
        Credentials:
            description:
                TBC
            properties:
                keyStoreCredentialPassword:
                    type: string
                    writeOnly: true
        Error:
            properties:
                message:
                    example: No CommerceCurrency exists with the key {groupId=41811, code=US Dollar}
                    readOnly: true
                    type: string
                status:
                    description:
                        HTTP Status code
                    example: 404
                    readOnly: true
                    type: integer
            required:
                - message
                - status
            type: object
        Idp:
            # @review
            description:
                Configuration of the SAML provider's IDP capability
            properties:
                authnRequestSignatureRequired:
                    type: boolean
                defaultAssertionLifetime:
                    type: integer
                sessionMaximumAge:
                    format: int64
                    type: integer
                sessionTimeout:
                    format: int64
                    type: integer
                spConnections:
                    description:
                        Connected SAML SPs
                    items:
                        $ref: "#/components/schemas/SpConnection"
                    type: array
            type: object
        IdpConnection:
            # @review
            description:
                Connection details for a connected SAML IDP
            properties:
                assertionSignatureRequired:
                    type: boolean
                clockSkew:
                    format: int64
                    type: integer
                enabled:
                    type: boolean
                entityId:
                    type: string
                forceAuthn:
                    type: boolean
                id:
                    format: int64
                    type: integer
                metadataUpdatedDate:
                    format: date-time
                    readOnly: true
                    type: string
                metadataUrl:
                    type: string
                metadataXml:
                    type: string
                name:
                    type: string
                nameIdFormat:
                    type: string
                signAuthnRequest:
                    type: boolean
                unknownUsersAreStrangers:
                    type: boolean
                userAttributeMappings:
                    type: string
            type: object
        SamlProvider:
            description:
                Dummy schema which can be referenced from tags
            properties:
                enabled:
                    type: boolean
                entityId:
                    type: string
                idp:
                    $ref: "#/components/schemas/Idp"
                role:
                    enum: [idp, sp]
                    type: string
                signMetadata:
                    type: boolean
                sp:
                    $ref: "#/components/schemas/Sp"
                sslRequired:
                    type: boolean
            type: object
        Sp:
            # @review
            description:
                Configuration of the SAML provider's SP capability
            properties:
                allowShowingTheLoginPortlet:
                    type: boolean
                assertionSignatureRequired:
                    type: boolean
                clockSkew:
                    format: int64
                    type: integer
                idpConnections:
                    description:
                        Connected SAML IDPs
                    items:
                        $ref: "#/components/schemas/IdpConnection"
                    type: array
                ldapImportEnabled:
                    type: boolean
                signAuthnRequest:
                    type: boolean
            type: object
        SpConnection:
            # @review
            description:
                Connection details for a connected SAML SP
            properties:
                enabled:
                    type: boolean
            type: object
info:
    description:
        "SAML configuration. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.saml.admin.rest.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Headless Admin SAML"
    version: v1.0
openapi: 3.0.1
paths:
    "/idpConnections":
        get:
            # @review
            description:
                Retrieves the connected SAML IDPs
            operationId: getIdpConnections
            parameters:
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/IdpConnection"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/IdpConnection"
                                type: array
            tags: ["IdpConnection"]
        post:
            description:
                Creates a new SAML IDP connection
            operationId: postIdpConnection
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/IdpConnection"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/IdpConnection"
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
                    # @review
                    description:
                        "SAML SP IDP connection successfully created"
            tags: ["IdpConnection"]
    "/idpConnections/{idpConnectionId}":
        delete:
            # @review
            description:
                Deletes the SAML IDP connection
            operationId: deleteIdpConnection
            parameters:
                - in: path
                  name: idpConnectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["IdpConnection"]
        get:
            description:
                Retrieves the SAML IDP connection.
            operationId: getIdpConnection
            parameters:
                - in: path
                  name: idpConnectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
            tags: ["IdpConnection"]
        patch:
            description:
                Updates the SAML IDP Connection with information sent in the request body. Only the provided fields are
                updated.
            operationId: patchIdpConnection
            parameters:
                - in: path
                  name: idpConnectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/IdpConnection"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/IdpConnection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
                    # @review
                    description:
                        "SAML SP IDP connection successfully created"
            tags: ["IdpConnection"]
        put:
            description:
                Replaces the SAML IDP connection with information sent in the request body. Any missing fields are
                deleted unless they are required.
            operationId: putIdpConnection
            parameters:
                - in: path
                  name: idpConnectionId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/IdpConnection"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/IdpConnection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/IdpConnection"
                    # @review
                    description:
                        "SAML SP IDP connection successfully created"
            tags: ["IdpConnection"]
    "/provider":
        get:
            description:
                Retrieves the SAML Provider configuration.
            operationId: getSamlProvider
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SamlProvider"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SamlProvider"
            tags: ["SamlProvider"]
        patch:
            description:
                Patch the SAML Provider configuration.
            operationId: patchSamlProvider
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SamlProvider"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SamlProvider"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SamlProvider"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SamlProvider"
                    # @review
                    description:
                        "SAML provider configuration was successfully created"
                400:
                    contents:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Error"
                    # @review
                    description:
                        "Invalid input"
            tags: ["SamlProvider"]
        post:
            description:
                Creates a full SAML Provider configuration with peer connections.
            operationId: postSamlProvider
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SamlProvider"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/SamlProvider"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SamlProvider"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/SamlProvider"
                    # @review
                    description:
                        "SAML provider configuration was successfully created"
            tags: ["SamlProvider"]
    "/provider/{roleId}":
        delete:
            description:
                Delete the SAML SP Provider configuration.
            operationId: deleteRole
            parameters:
                - in: path
                  name: roleId
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["SamlProvider"]
        get:
            description:
                Retrieves the SAML SP Provider configuration.
            operationId: getRole
            parameters:
                - in: path
                  name: roleId
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/Idp"
                                    - $ref: "#/components/schemas/Sp"
                        application/xml:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/Idp"
                                    - $ref: "#/components/schemas/Sp"
            tags: ["SamlProvider"]
        patch:
            description:
                Patch the SAML SP Provider configuration.
            operationId: patchRole
            parameters:
                - in: path
                  name: roleId
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            oneOf:
                                - $ref: "#/components/schemas/Idp"
                                - $ref: "#/components/schemas/Sp"
                    application/xml:
                        schema:
                            oneOf:
                                - $ref: "#/components/schemas/Idp"
                                - $ref: "#/components/schemas/Sp"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/Idp"
                                    - $ref: "#/components/schemas/Sp"
                        application/xml:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/Idp"
                                    - $ref: "#/components/schemas/Sp"
                    # @review
                    description:
                        "SAML provider configuration was successfully created"
            tags: ["SamlProvider"]
        put:
            description:
                Replaces the SAML SP Provider configuration.
            operationId: putRole
            parameters:
                - in: path
                  name: roleId
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            oneOf:
                                - $ref: "#/components/schemas/Idp"
                                - $ref: "#/components/schemas/Sp"
                    application/xml:
                        schema:
                            oneOf:
                                - $ref: "#/components/schemas/Idp"
                                - $ref: "#/components/schemas/Sp"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/Idp"
                                    - $ref: "#/components/schemas/Sp"
                        application/xml:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/Idp"
                                    - $ref: "#/components/schemas/Sp"
                    # @review
                    description:
                        "SAML provider configuration was successfully created"
            tags: ["SamlProvider"]