author=Liferay, Inc.
change-log=
licenses=
liferay-portal-profile-names=
liferay-versions=7.0.10+,7.1.0+
long-description=OAuth2 Provider hook
module-group-id=liferay
module-incremental-version=4
name=OAuth2 Provider hook
page-url=http://www.liferay.com
short-description=
tags=oauth2, authorization, delegation